### ISSUE TITLE
--print-removed with empty results still prints something

### ISSUE THREAD

**Issue by ahmetb** [b23llc/kubectl-config-cleanup#2]
```
kubectl config-cleanup --print-removed
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

it prints empty context entry, despite removing nothing. I expect an empty output.

**Comment by dbkegley** [comment]
Makes sense. What about the inverse? When all clusters/users/contexts are removed and the `--print-removed` flag is not used, do you expect nothing or an empty kubeconfig?

**Comment by ahmetb** [comment]
I probably never want to deal with an empty object with fields. I'd rather get empty output.
